name: p6_base
description: Generic package for P6 project
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  json_annotation: ^4.8.1
  package_info_plus: ^4.0.0
  path_provider: ^2.0.15
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.0
  json_serializable: ^6.2.0

flutter:
