name: Pawsome Programmable Personal Penguin Patch Patrol
on:
  push:
    branches: [ "main", "stage" ]
  pull_request:
    branches: [ "main", "stage" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.9'
          channel: 'stable'

      - name: Install dependencies (main)
        run: flutter pub get
      - name: Install dependencies (base)
        run: cd p6_base && flutter pub get
      - name: Install dependencies (connect)
        run: cd p6_connect && flutter pub get
      - name: Install dependencies (ui)
        run: cd p6_ui && flutter pub get

      - name: Build Windows
        run: flutter build windows
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.9'
          channel: 'stable'

      - name: Flutter version
        run: flutter --version
      - name: flutter doctor
        run: flutter doctor

      - name: Install dependencies (main)
        run: flutter pub get
      - name: Install dependencies (base)
        run: cd p6_base && flutter pub get
      - name: Install dependencies (connect)
        run: cd p6_connect && flutter pub get
      - name: Install dependencies (ui)
        run: cd p6_ui && flutter pub get

      - name: Analyze project source
        run: flutter analyze
      - name: Run tests
        run: flutter test
